services:
  nginx:
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - WordPress:/var/www/html
    env_file:
      - .env
    secrets:
      - nginx_key
      - nginx_crt
    restart: unless-stopped

  wordpress:
    depends_on:
      mariadb:
        condition: service_healthy
    build:
      context: ./requirements/wordpress
    volumes:
      - WordPress:/var/www/html
    env_file:
      - .env
    environment:
      WP_ADMIN_PASSWORD_FILE: /run/secrets/wp_admin_password
      WP_USER1_PASSWORD_FILE: /run/secrets/wp_user1_password
      DB_ADMIN_PASSWORD_FILE: /run/secrets/db_admin_password
    secrets:
      - wp_admin_password
      - wp_user1_password
      - db_admin_password
    restart: unless-stopped


  mariadb:
    build:
      context: ./requirements/mariadb
    volumes:
      - DB:/var/lib/mysql
    env_file:
      - .env
    environment:
      DB_ADMIN_PASSWORD_FILE: /run/secrets/db_admin_password
      DB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      DB_DEFAULT_USER_PASSWORD_FILE: /run/secrets/db_default_user_password
    secrets:
      - db_admin_password
      - db_root_password
      - db_default_user_password
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uhealth -phealthpass -h 127.0.0.1 --silent || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 20s
    restart: unless-stopped

#[D6]
volumes:
  WordPress:
    name: WordPress
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/mvan-rij/data/WordPress
  DB:
    name: DB
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/mvan-rij/data/DB

#[D3]
secrets:
  wp_user1_password:
    file: ./secrets/wp_user1_password.txt
  wp_admin_password:
    file: ./secrets/wp_admin_password.txt
  db_admin_password:
    file: ./secrets/db_admin_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_default_user_password:
    file: ./secrets/db_default_user_password.txt
  nginx_crt:
    file: ./secrets/inception.crt
  nginx_key:
    file: ./secrets/inception.key

networks:
  inception:
    name: inception